#!/usr/bin/env zsh
pick() {
    local arg1="$1"
    local arg2="$2"

    # editor is one of "edit", "code" if available 
    

    echo "TODO: would pick a file and opening type and suggest available editors"
}