#!/usr/bin/env zsh
not-found-process() {
    local command=$1
    # local isAtLeast3Args=false
    # if [[ $# -ge 3 ]]; then
    #     isAtLeast3Args=true
    # fi
    shift 1
    local prefix="$(format-cmd "not-found-process")"
    local returnCode=$CODE_NOT_FOUND

    #? check if x-${command} exists
    if command-exists "x-${command}"; then
        echo-debug "$prefix Command $(format-cmd "x-${command}") found. Running it with args: $(format-args "$@")"
        x-${command} $@
        return $?
    fi

    #? check if can be run as script at scripts folder
    script-run "$SHULKER_DIR/scripts/$command" $@
    returnCode=$?
    if [[ $returnCode -ne $CODE_NOT_FOUND ]]; then
        echo-debug "$prefix Command $(format-cmd "$command") found and executed successfully."
        return $returnCode
    fi

    #? check if can be run as script at current directory
    script-run "$PWD/$command" $@
    returnCode=$?
    if [[ $returnCode -ne $CODE_NOT_FOUND ]]; then
        echo-debug "$prefix Command $(format-cmd "$command") found and executed successfully."
        return $returnCode
    fi

    #? check if can be run as FE script defined in package.json
    pkg-manager-exists $command
    returnCode=$?
    if [[ $returnCode -ne $CODE_NOT_FOUND ]]; then
        pkg-manager-run $command $@
        returnCode=$?
        return $returnCode
    fi

    #? if 3 or more words are passed, assume the command is a valid AI command
    # if [[ $isAtLeast3Args == true ]]; then
    #     ai $command $restArgs
    #     return $?
    # fi

    echo-debug "$prefix Command $(format-cmd "$command") not found. Args: $(format-args "$@")"
    return $CODE_NOT_FOUND
}