#!/usr/bin/env zsh
export HOMEBREW_NO_ENV_HINTS=1

ZAP_DIR="$HOME/.local/share/zap"
ZSH_AUTOSUGGEST_PATH="$ZAP_DIR/plugins/zsh-autosuggestions"

export NVM_DIR="$HOME/.nvm"

export LUA_PATH="$SHULKER_DIR/lua/?.lua;;"
