#!/usr/bin/env zsh
shu-run-at() {
    local prefix="$(format-cmd "shu-run-at")"

    echo-debug "$prefix All args: $@"

    local currentDir="$1"
    local currentCmd="$2"
    local restArgs="${@:3}"


    echo-debug "$prefix Current dir: $(format-args "$currentDir")"
    echo-debug "$prefix Current command: $(format-args "$currentCmd")"
    echo-debug "$prefix Rest args: $(format-args "$restArgs")"

    local cmdDir=$currentDir/$currentCmd
    local cmdDirFormatted=$(format-args "$cmdDir")

    if [[ -d "$currentDir/$currentCmd" ]]; then
        echo-debug "$prefix Directory exists: $cmdDirFormatted"
        shu-run-at "$currentDir/$currentCmd" "$restArgs"
        return $?
    else
        echo-debug "$prefix Directory does not exist: $cmdDirFormatted, running as command file"
        script-run "$currentDir/$currentCmd" "$restArgs"
        return $?
    fi
}