#!/usr/bin/env zsh
linker-link() {
    local prefix=$(format-cmd "linker-link")
    echo-info "$prefix Linking directories and files..."

    local files_list=$(linker-list-files)
    if [[ -z $files_list ]]; then
        echo-error "$prefix No files to link."
        return $CODE_ERROR
    fi

    while IFS= read -r line; do
        local key="${line%%|*}"
        local value="${line#*|}"
        link-file "$key" "$value"
    done <<< "$files_list"
}