#!/usr/bin/env zsh
linker-add() {
    local prefix=$(format-cmd "linker-add")
    local keyProp="$1"
    local valueProp="$2"
    echo-debug "$prefix Add link $(format-args $keyProp)=$(format-args $valueProp)"
    linker_list[$keyProp]="$valueProp"
    return $CODE_OK
}