#? base colors
COLOR_CYAN="$(color-hex "#00FFFF")"
COLOR_DARK_RED="$(color-hex "#FF3131")"
COLOR_YELLOW="$(color-hex "#FFFF00")"
COLOR_HOTPINK="$(color-hex "#FF00AF")"
COLOR_GREEN="$(color-hex "#00FF00")"
COLOR_MAGENTA="$(color-hex "#C965C9")"
COLOR_WHITE="$(color-hex "#FFFFFF")"
COLOR_DARK_BLUE="$(color-hex "#0000FF")"
COLOR_DARK_GREEN="$(color-hex "#00FF00")"
COLOR_DARK_YELLOW="$(color-hex "#FFFF00")"
COLOR_DARK_CYAN="$(color-hex "#00FFFF")"
COLOR_DARK_MAGENTA="$(color-hex "#FF00FF")"
COLOR_DARK_WHITE="$(color-hex "#FFFFFF")"
COLOR_DARK_GRAY="$(color-hex "#808080")"
COLOR_DARK_ORANGE="$(color-hex "#FFA500")"
COLOR_DARK_PINK="$(color-hex "#FF69B4")"
COLOR_DARK_PURPLE="$(color-hex "#800080")"
COLOR_DARK_TURQUOISE="$(color-hex "#40E0D0")"

#? semantic colors
COLOR_COMMAND="$COLOR_CYAN"
COLOR_INFO="$COLOR_CYAN"
COLOR_ARGUMENT="$COLOR_YELLOW"
COLOR_PARAMS="$COLOR_DARK_PINK"
COLOR_SUCCESS="$COLOR_GREEN"
COLOR_ERROR="$COLOR_DARK_RED"
COLOR_DEBUG="$COLOR_MAGENTA"
COLOR_WARNING="$COLOR_DARK_ORANGE"

#? styles
STYLE_RESET="\033[0m"
STYLE_BOLD="\033[1m"

#? aliases
COLOR_ARGS="$COLOR_ARGUMENT"
COLOR_ARG="$COLOR_ARGUMENT"