#!/usr/bin/env zsh
compile-raw-directory() {
    local sourceDir="$1"
    local targetFile="$2"

    local prefix=$(format-cmd 'compile-raw-directory')
    local sourceDirFormatted=$(format-args "$sourceDir")
    local targetFileFormatted=$(format-args "$targetFile")

    if [[ ! -d "$sourceDir" ]]; then
        echo-debug "$prefix Source directory does not exist: $sourceDirFormatted"
        return $CODE_OK
    fi

    local files_list=()
    compile-raw-directory-mapper() {
        local file="$1"
        if [[ -f "$file" ]]; then
            echo-verbose-debug "$prefix Add file: $(format-args "$file")"
            files_list+=("$file")
            # source "$file"
        fi
    }

    each-sh-recursive "$sourceDir" "compile-raw-directory-mapper"
    awk 'FNR==1 && NR!=1 {print ""} {print}' "${files_list[@]}" > "$targetFile"
    echo-debug "$prefix Compiled raw directory: $sourceDirFormatted to file: $targetFileFormatted"
    trace-add "$prefix Compiled $sourceDirFormatted to file: $targetFileFormatted"
}