#!/usr/bin/env zsh
script-run() {
    local currentCmd=$1
    shift 1

    local prefix="$(format-cmd "script-run")"

    local currentCmdFormatted=$(format-args "$currentCmd")
    local restArgsFormatted=$(format-args "$@")

    echo-debug "$prefix Current command: $currentCmdFormatted"
    echo-debug "$prefix Rest args: $restArgsFormatted"

    local returnCode=$CODE_NOT_FOUND

    for ext in sh zsh lua ts; do
        script-run-by-extension "$ext" "$currentCmd" "$@"
        returnCode=$?
        if [[ $returnCode -ne $CODE_NOT_FOUND ]]; then
            echo-debug "$prefix $currentCmdFormatted Return code is $returnCode for extension $ext"
            return $returnCode
        fi
    done

    if [[ -f "$currentCmd" ]]; then
        script-run-noext "$currentCmd" "$@"
        returnCode=$?
        if [[ $returnCode -ne $CODE_NOT_FOUND ]]; then
            echo-debug "$prefix $currentCmdFormatted Return code is $returnCode for noext"
            return $returnCode
        fi
    fi

    return $CODE_NOT_FOUND
}