#!/usr/bin/env zsh
script-run-noext() {
    local prefix="$(format-cmd "script-run-noext")"
    local pathToCmd="$1"
    if [[ -f $pathToCmd ]]; then
        shift 1
        echo-debug "$prefix Script $(format-args "$ext") at $(format-args "$pathToCmd") with args: $(format-args "$@")"
        # chmod +x "$pathToCmd"
        $pathToCmd "$@"
        return $?
    fi
    echo-debug "$prefix Script $(format-args "$ext") at $(format-args "$pathToCmd") not found."
    return $CODE_NOT_FOUND
}