#!/usr/bin/env zsh
load-nvm() {
    local prefix=$(format-cmd 'load-nvm')
    local start_time=$(get-time-ms)

    if [[ ! -d "$NVM_DIR" ]]; then
        echo-info "NVM does not exist at $NVM_DIR, installing..."
        PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
    fi
    unset-nvm-overrides
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm ( --no-use)
    # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    local end_time=$(get-time-ms)
    local elapsed_time=$((end_time - start_time))
    trace-add "$prefix NVM loaded in $(format-args "$elapsed_time") ms"
    load-nvm() {
        #? only load once
    }
}